
[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "dfinsight"
version = "0.1.0"
description = "A lightweight data quality and dataset inspection library for pandas DataFrames"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pandas>=1.5"
]
